# File is taken from https://gist.github.com/doaa-altarawy/9e324f2486e53d38de817e0e38e58175
# For more configuration details:
# https://docs.codecov.io/docs/codecov-yaml

# Check if this file is valid by running in bash:
# curl -X POST --data-binary @.codecov.yml https://codecov.io/validate

# Ignoring Paths
# --------------
# which folders/files to ignore
ignore:
  - "*/tests/.*"
  - "setup.py"
