lsi: false
safe: true
incremental: false
highlighter: rouge

title: fasttrees
description: A fast-and-frugal-tree classifier based on Python's scikit learn
theme: just-the-docs

url: https://fasttrees.github.io/fasttrees/

aux_links:
  Template Repository: https://fasttrees.github.io/fasttrees/

gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge


plugins:
  - jekyll-default-layout
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
